galaxy-a:
  image: bgruening/galaxy-stable
  expose:
    - 80

galaxy-b:
  image: bgruening/galaxy-stable
  expose:
    - 80

galaxy-c:
  image: bgruening/galaxy-stable
  expose:
    - 80

galaxy-haproxy:
  build: galaxy-haproxy
  volumes:
   - galaxy-haproxy:/haproxy-override
  links:
   - galaxy-a
   - galaxy-b
   - galaxy-c
  ports:
   - "9080:80"
   - "9070:70"
  expose:
   - "80"
   - "70"


