apiVersion: v1
kind: Service
metadata:
  name: galaxy-service
  labels:
    app: galaxy
spec:
  selector:
    app: galaxy
  type: NodePort
  ports:
  - port: 9080
    targetPort: 80
    protocol: TCP
  sessionAffinity: ClientIP
  clusterIP: 10.0.0.101
#  loadBalancerIP: 192.168.0.175
#  externalIPs: [ "192.168.0.175" ]
#  type: LoadBalancer

